version: 2.1

jobs:
  build:
    docker:
      - image: ruby:3.1  # Rubyの公式イメージ
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: |
            gem install bundler -v 2.5.16
      - run:
          name: Install dependencies
          command: |
            bundle install
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  version: 2
  build_only:
    jobs:
      - build
